export const homeObjOne = {
  id: 'projects',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Portfolio',
  heading: 'Projects',
  description: 'Below are the projects I\'ve created',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/prj-color.jpg').default,
  alt: 'Color Project',
  dark: true,
  primary: true,
  darkText: true,
}

export const homeObjTwo = {
  id: 'projects',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Portfolio',
  heading: 'Projects',
  description: 'Below are the projects I\'ve created',
  buttonLabel: 'Get started',
  imgStart: true,
  img: require('../../images/prj-dice.jpg').default,
  alt: 'Color Project',
  dark: true,
  primary: true,
  darkText: true,
}

export const homeObjThree = {
  id: 'projects',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Portfolio',
  heading: 'Projects',
  description: 'Below are the projects I\'ve created',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/prj-movie.jpg').default,
  alt: 'Color Project',
  dark: true,
  primary: true,
  darkText: true,
}
export const about = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'About',
  heading: 'About',
  description: 'Below are the projects I\'ve created',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/profile.png').default,
  alt: 'Color Project',
  dark: true,
  primary: true,
  darkText: true,
}
export const contact = {
  id: 'contact',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Portfolio',
  heading: 'Projects',
  description: 'Below are the projects I\'ve created',
  buttonLabel: 'Get started',
  imgStart: false,
  alt: 'Color Project',
  dark: true,
  primary: true,
  darkText: false,
}